inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'

Layout/LineLength:
  Max: 170

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Style/Lambda:
  EnforcedStyle: lambda

Style/SymbolArray:
  EnforcedStyle: brackets

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
