# TODO: gradually revisit these settings.
# Ideally the code should be refactored so that this file will be empty

Metrics/ParameterLists:
  Max: 30

Metrics/BlockNesting:
  Max: 4

Metrics/ModuleLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 80

RSpec/ExampleLength:
  Max: 40

RSpec/MultipleExpectations:
  Max: 20

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

ThreadSafety/InstanceVariableInClassMethod:
  Enabled: false

ThreadSafety/NewThread:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Naming/ClassAndModuleCamelCase:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

ThreadSafety/ClassAndModuleAttributes:
  Enabled: false

Naming/FileName:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
