inherit_from: .rubocop_todo.yml

inherit_gem:
  mapotempo_rubocop:
    - rubocop-default.yml

require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.0
  CacheRootDirectory: rubocop_cache
  Exclude:
    - 'tmp/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'