name: base benchmark
on:
  push:
    branches:
      - master

jobs:
  benchmark_base_branch:
    name: Continuous Benchmarking with Bencher
    permissions:
      checks: write
    strategy:
      matrix:
        include:
          - ruby: '2.7'
            gemfile: '5.2.7'
            couchbase: '7.1.0'
          - ruby: '2.7'
            gemfile: '6.0.0'
            couchbase: '7.1.0'
          - ruby: '2.7'
            gemfile: '6.0.0'
            couchbase: '7.6.3'
          - ruby: '2.7'
            gemfile: '7.0.0'
            couchbase: '7.1.0'
          - ruby: '2.7'
            gemfile: '7.0.0'
            couchbase: '7.6.3'
          # ruby 3.0 minimimun required rails 6.0.3
          # - ruby: '3.0' 
          #   gemfile: '5.2.7'
          #   couchbase: '7.1.0'
          - ruby: '3.0'
            gemfile: '6.1.7.7'
            couchbase: '7.1.0'
          - ruby: '3.0'
            gemfile: '7.0.0'
            couchbase: '7.1.0'
          - ruby: '3.0'
            gemfile: '7.0.0'
            couchbase: '7.6.3'
      fail-fast: false
    runs-on: ubuntu-22.04
    name: ${{ matrix.ruby }} rails-${{ matrix.gemfile }}  couchbase-${{ matrix.couchbase }}
    steps:
    - uses: actions/checkout@v4
    - uses: bencherdev/bencher@main
    - run: sudo apt-get update && sudo apt-get install libevent-dev libev-dev libtinfo5
    - name: Downgrade to CMake 3.27
      run: |
        sudo apt-get remove -y cmake
        wget https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.sh
        chmod +x cmake-3.27.9-linux-x86_64.sh
        sudo ./cmake-3.27.9-linux-x86_64.sh --skip-license --prefix=/usr/local
    - run: cmake --version
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo ./ci/run_couchbase.sh $COUCHBASE_VERSION $COUCHBASE_BUCKET $COUCHBASE_USER $COUCHBASE_PASSWORD
    - name: Track base branch benchmarks with Bencher
      run: |
        cd perf && \
        bencher run \
        --project mapotempo-couchbase-orm \
        --token '${{ secrets.BENCHER_API_TOKEN }}' \
        --branch master \
        --testbed ubuntu-22.04 \
        --adapter ruby_benchmark \
        --github-actions '${{ secrets.GITHUB_TOKEN }}' \
        --ruby-version $RUBY_VERSION \
        --gemfile $ACTIVE_MODEL_VERSION \
        --couchbase-version $COUCHBASE_VERSION \
        bundle exec ruby benchmark.rb
    env:
        ACTIVE_MODEL_VERSION: ${{ matrix.gemfile }}
        BUNDLE_JOBS: 4
        BUNDLE_PATH: vendor/bundle
        COUCHBASE_BUCKET: default
        COUCHBASE_USER: tester
        COUCHBASE_PASSWORD: password123
        COUCHBASE_VERSION: ${{ matrix.couchbase }}
        RUBY_VERSION: ${{ matrix.ruby }}