name: documentation

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Downgrade to CMake 3.27
        run: |
          sudo apt-get remove -y cmake
          wget https://github.com/Kitware/CMake/releases/download/v3.27.9/cmake-3.27.9-linux-x86_64.sh
          chmod +x cmake-3.27.9-linux-x86_64.sh
          sudo ./cmake-3.27.9-linux-x86_64.sh --skip-license --prefix=/usr/local
      - run: cmake --version
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme
      - name: Sphinx build
        run: |
          cd docs/
          make html
          cd ..
      - name: Yard Doc build
        run: |
          bundle exec yard
      - name: Merge Doc
        run: |
          mkdir docs/_build/html/api 
          mv yard_docs/* docs/_build/html/api
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          public_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true

