name: documentation

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme
      - name: Sphinx build
        run: |
          cd docs/
          make html
          cd ..
      - name: Yard Doc build
        run: |
          bundle exec yard
      - name: Merge Doc
        run: |
          mv yard_docs/* docs/_build/html/api
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          public_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true

